vich_uploader:
    db_driver: orm

    mappings:
        profil:
            uri_prefix: /Fondation/images/profils
            upload_destination: '%kernel.project_dir%/public/images/profils'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
